### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ChGalle** [HappyTobi/warp#5]
Hi, 

wäre es möglich den PDF-Export des Charge-Logs noch zeitlich einzuschränken? 

Beispielsweise vom 01.07 - 31.07 etc. ?

Bin leider in Go überhaupt nicht im Bilde...

Grüße

Christoph

**Comment by HappyTobi** [comment]
Hi @ChGalle 

also es ist aktuell schon möglich den Export einzuschränken.

```bash
/warp charge-tracker log --help

...

Flags:
  -f, --file string     Output file (default: stdout)
  -h, --help            help for log
  -m, --month int       Filter by month (format: 1...12) (default -1)
  -o, --output string   Output format (json, yaml,csv) (default "json")
  -r, --user string     Filter by username (case-insensitive)
  -y, --year int        Filter by year (format: YYYY) (default -1)
...
```

Du kannst z.B. wie folgt den Monat August exportieren.

```bash
/warp charge-tracker log -f ./test.pdf -o pdf  -m 8 -c http://ip
```

Reicht dir ein export auf einen bestimmten Monat oder ist der Tag auch noch relevant.

Gruß Tobi

**Comment by ChGalle** [comment]
Hi @HappyTobi!

Wer lesen kann ist klar im Vorteil! 
Vielen Dank für die schnelle Info! 
Nein, so passt alles für mich!

Grüße

Christoph
